pygments: true
exclude: [
  README.md,
  package.json,
  gruntfile.js,
  sass/
]

paginate: 5

url: http://tech.zumba.com
career_email: engineering@zumba.com
engineer_email: engineering@zumba.com

permalink: /:year/:month/:day/:title/

disqus_short_name: zumbaengineering

analytics_code: UA-33869562-1

share_twitter: true
share_google: true
share_facebook: false
share_reddit: true

# Put the authors in alphabetical order
authors:
  cjsaylor:
    name: Chris Saylor
    email: christopher.saylor@zumba.com
    position: Lead Developer
    start_date: 2011-02-01
    github: cjsaylor
    twitter: cjsaylor
    gplus: 104913325876410476247
    gravatar: 53c40ddf10f397ab4494fc55078125dc
    about: Besides Zumba<sup>&reg;</sup>, he is the author of the
      <span itemscope itemtype="http://schema.org/MobileApplication"><a href="http://boxmeupapp.com/" itemprop="url"><span itemprop="name">Boxmeup</span></a></span>."
      Loves <a href="http://nodejs.org">Node.js</a> and has couple of open source application using this plataform.
  jrbasso:
    name: Juan Basso
    email: juan.basso@zumba.com
    position: Technical Architect
    start_date: 2010-12-01
    github: jrbasso
    twitter: jrbasso
    gplus: 105859985385247388276
    gravatar: 1333d11249a2ed342d612c49a7c1e913
    about: Besides Zumba<sup>&reg;</sup>, he is core developer of <a href="http://cakephp.org">CakePHP framework</a> and author of many CakePHP plugins. Likes code quality, standards, and crazy for performance.
  young-steveo:
    name: Stephen Young
    email: stephen.young@zumba.com
    position: Senior Software Engineer
    start_date: 2012-12-03
    github: young-steveo
    twitter: young_steveo
    gplus: 116989823921363664764
    gravatar: 3bf295323fca7f0e92a65d11f07b032e
    about: Besides Zumba<sup>&reg;</sup>, he is an avid gamer and likes to tinker with Javascript technologies.  He recently developed <a href="https://github.com/young-steveo/chainable.js">chainable.js</a> and <a href="https://github.com/young-steveo/bitmask.js">bitmask.js</a>.
  juliancc:
    name: Julian Castaneda
    email: julian.castaneda@zumba.com
    position: Senior Software Engineer
    start_date: 2012-12-03
    github: juliancc
    twitter: juliancc
    gravatar: 454c4cbd40877eaf37790af917092093
    about: Besides Zumba<sup>&reg;</sup>, he is seen at local music shows and traveling around the world on his time off.
  neptunz:
    name: Kaue Ribeiro
    email: kaue.ribeiro@zumba.com
    position: Lead Software Engineer
    start_date: 2012-12-10
    github: neptunz
    twitter: kaue_ribeiro
    gravatar: db2fd68cfe07d114323af92c338207f8
    about: Besides Zumba<sup>&reg;</sup>, he is often designing, developing, playing basketball and laughing for no reason. <a href="dribbble.com/Kaue_Ribeiro">Dribbble</a>
  aramonc:
    name: Adrian Cardenas
    email: adrian.cardenas@zumba.com
    position: Software Engineer
    start_date: 2014-08-25
    github: aramonc
    twitter: aramonc
    gravatar: c41323a7dc18ea64a7f617e85ffb8c9a
    about: Besides Zumba<sup>&reg;</sup>, he is one of the co-organizers of the SoFloPHP users group, the SunshinePHP conference, and one of the technical leads for Code for Miami, a Code for America brigade.
  nkcmr:
    name: Nick Comer
    email: nicholas@zumba.com
    position: Software Engineer
    start_date: 2015-01-05
    github: nkcmr
    twitter: nkcmr
    gravatar: 6cfd0f092823a5c90f93944cdfeb5d9d
    about: Besides Zumba<sup>&reg;</sup>, he is usually outside, kayaking, biking or taking pictures of stuff. Or you might find him keeping busy with other projects.
  ZumbaJustin:
    name: Justin Oakley
    email: justin.oakley@zumba.com
    position: Software Engineer
    start_date: 2015-03-30
    github: ZumbaJustin
    twitter: lordtakuban
    gravatar: 8bf94254d96ded534cbb3a70540bfe84
    about: Besides Zumba<sup>&reg;</sup>, he is working on various side projects.
      Prior to the world of business application development, he worked on video games (<a href="http://imdb.com/name/nm2035116/">IMDB - Justin Oalkey</a>).
      When not developing software, you may find him modifying one of his cars (<a href="http://www.mr2ner.com">MR2ner</a> | <a href="http://www.myhachiroku.com">My Hachi Roku</a>) or autocrossing.

#job listings
jobs:
  sr_soft_eng:
    name: Senior Software Engineer
    slug: sr_soft_eng
    responsibilities:
      - "Analyze application requirements and provide recommended technical design solutions that are efficient, scalable, maintainable, and accurately meet the needs of the business."
      - "Design new features capable of handling thousands of requests/minute."
      - "Design small to medium sized project solutions that are modular and scalable."
      - "Build web services to support a wide range of products/services in a multi-server environment."
      - "Develop and continuously enhance Zumba web and related applications and refactor existing business logic into reusable services."
      - "Build and maintain membership, ecommerce, and web platforms."
      - "Document existing processes."
      - "Document new architecture and design and code."
      - "Participate in resolving challenging and demanding problems within the production environment."
      - "Ensure SLA metrics (performance, availability, usage, and security) are met."
      - "Assist with customer inquiries and resolution of problems."
      - "Research, prototype, and make recommendations on software tools, new approaches and new technologies and alternative ways to better accomplish functional requests."
    requirements:
      - "5+ years of software design and development experience."
      - "At least 2 years as a php developer."
      - "4 year Bachelor’s degree in Computer Science or related experience."
      - "Experience using web frameworks."
      - "Experience with Agile development methodologies, especially SCRUM."
      - "Strong oral and written communication skills, and must be able to work effectively with management, customers and technical staff in analyzing situations and resolving issues."
      - "Must be able to work independently as well as with a team."
      - "Motivated, self directed, but with the ability to take direction from others."
      - "Strong analysis skills with a thorough understanding of application and infrastructure bottlenecks."
      - "Able to clearly document and communicate a design to team members."
      - "Experienced supporting a production application, including deployments, troubleshooting, and tuning."
      - "Strong PHP 5.3+ skills and knowledge of PHP’s OOP principles."
      - "Excellent knowledge of object oriented analysis, design and programming (OOA/OOD/OOP), MVC and other design patterns."
      - "Must be proficient with SSCS, preferably Git."
      - "Experienced designing and building Web Services, and integrations with third parties through APIs, SOAP, OAuth, etc)."
      - "Experienced building unit tests and unit test frameworks."
      - "Able to multitask and resolve multi-faceted issues with creativity and minimum direction."
      - "Able to understand business problems, and be creative with strong problem solving abilities."
      - "Able to design and build secure, scalable, reliable, and well-tuned systems."
    desireable:
      - "Experience working for a major internet company and knowledge of ecommerce sites is a huge plus."
      - "Jira, RallyDev"
      - "Experience in contributing to and interest in Opensource technology."
  soft_eng:
    name: Software Engineer
    slug: soft_eng
    responsibilities:
      - "Analyze application requirements and provide recommended technical design solutions that are efficient, scalable, maintainable, and accurately meet the needs of the business."
      - "Design new features capable of handling thousands of requests/minute."
      - "Design small to medium sized project solutions that are modular and scalable."
      - "Build web services to support a wide range of products/services in a multi-server environment."
      - "Develop and continuously enhance Zumba web and related applications and refactor existing business logic into reusable services."
      - "Build and maintain membership, ecommerce, and web platforms."
      - "Document existing processes."
      - "Participate in resolving challenging and demanding problems within the production environment."
      - "Assist with customer inquiries and resolution of problems."
      - "Research, prototype, and make recommendations on software tools, new approaches and new technologies and alternative ways to better accomplish functional requests."
    requirements:
      - "3+ years of software design and development experience."
      - "At least 1 years as a php developer."
      - "4 year Bachelor’s degree in Computer Science or related experience."
      - "Experience using web frameworks."
      - "Experience with Agile development methodologies, especially SCRUM."
      - "Strong oral and written communication skills, and must be able to work effectively with management, customers and technical staff in analyzing situations and resolving issues."
      - "Must be able to work independently as well as with a team."
      - "Motivated, self directed, but with the ability to take direction from others."
      - "Strong analysis skills with a thorough understanding of application and infrastructure bottlenecks."
      - "Able to clearly document and communicate a design to team members."
      - "Experienced supporting a production application, including deployments, troubleshooting, and tuning."
      - "Strong PHP 5.3+ skills and knowledge of PHP’s OOP principles."
      - "Excellent knowledge of object oriented analysis, design and programming (OOA/OOD/OOP), MVC and other design patterns."
      - "Must be proficient with SSCS, preferably Git."
      - "Experienced designing and building Web Services, and integrations with third parties through APIs, SOAP, OAuth, etc)."
      - "Experienced building unit tests and unit test frameworks."
      - "Able to multitask and resolve multi-faceted issues with creativity and minimum direction."
      - "Able to understand business problems, and be creative with strong problem solving abilities."
      - "Able to design and build secure, scalable, reliable, and well-tuned systems."
    desireable:
      - "Experience working for a major internet company and knowledge of ecommerce sites is a huge plus."
      - "Jira, RallyDev"
      - "Experience in contributing to and interest in Opensource technology."
  fe_dev:
    name: Frontend Developer
    slug: fe_dev
    responsibilities:
      - "Analyze design requirements and provide recommended technical design solutions that are efficient, scalable, maintainable, and accurately meet the needs of the business."
      - "Participate in code, page weight, ADA compliance reviews."
      - "Develop complete micro sites from PSDs in a timely manner."
      - "Implement new features to an existing site."
      - "Debug our sites and applications whether it be a browser, styling or Javascript issue."
      - "Contribute to a development style guide."
      - "Review and contribute to Digital Design’s Style Guide."
      - "Participate in resolving challenging and demanding problems within the production environment."
      - "Ensure SLA metrics (performance, availability, usage, and security) are met."
      - "Assist with internal customer inquiries and resolution of problems."
      - "Research and make recommendations on software tools, new approaches and new technologies and alternative ways to better accomplish functional requests."
      - "Explore new technologies."
    requirements:
      - "4+ years in practical front-end development experience"
      - "4 year Bachelor’s degree in Computer Science or related experience"
      - "Must have an online portfolio"
      - "Must be an expert in hand-code clean, semantic, standards-compliant HTML5, CSS3/SASS and Javascript while still maintaining a fallback for browsers that don't support it (graceful degradation)."
      - "Must understand how to work in the console/Terminal"
      - "Familiar with working in a LAMP development environment and understand the basics of object oriented PHP"
      - "Must be an expert in developing responsive sites and applications."
      - "You understand how jQuery should &amp; can be used to enhance a site and its interactivity."
      - "Able to identify and tackle cross-browser quirks."
      - "Familiar with code versioning on Github."
      - "Experience with (or interest in) dynamic CSS preprocessors such as SASS."
      - "Ability to navigate Photoshop to translate into code."
      - "Ability to work closely with the UX/UI team to give feasibility and complexity feedback on wireframes and comps, as well as give suggestions for alternatives that might better fit the customer needs within the given timeframe."
      - "Experience with Agile development methodologies, especially SCRUM"
      - "You don't just \"cut things up\" -- you translate design into a brilliant user experience and you're not satisfied until it looks pixel-perfect."
      - "Passionate about writing logical, well-structured code that's easy to navigate."
      - "Experience in building mobile optimized web site"
      - "Ability to work with a team in and report to a Lead UI Developer"
      - "Ability to clearly document and communicate"
      - "Able to multitask and resolve multi-faceted issues with creativity and minimal direction"
      - "Able to understand business problems, and be creative with strong problem solving abilities."
    desireable:
      - "Experience producing FE code for ecommerce sites is a huge plus"
      - "Flexible and be able to handle multiple projects simultaneously"
      - "MS Visio or a similar tool, MS Word, MS Excel"
      - "Jira, RallyDev"
      - "Experience building front end code for ecommerce sites"
      - "Experience with web site Front End design and implementation."
      - "Tableless CSS, JavaScript, AJAX, XML, XSLT, XHTML"
      - "Experience with displaying XML content from a CMS"
      - "Experience with source code control systems (preferably Git)."
      - "Knowledge of industry-standard design tools such as Fireworks and Axure."
  devop_eng:
    name: DevOps Engineer
    slug: devop_eng
    responsibilities:
      - Master the overall site architecture and look for ways to improve our LAMP, storage and cloud infrastructures.
      - Grow and improve the infrastructure to handle scalability for rapid growth. Lead the adoption of the latest technologies for scaling a large web site
      - Create new tools to be used by our Development team for troubleshooting and automation.
      - Work with developers to remove scalability bottlenecks such as slow database queries, requests with high GC hit rates and memory leaks.
      - Working in an Agile/Scrum process with developers, maintain and improve testing and staging environments. Support QA function by enabling automated testing, continuous deployments and optimizing the release process.
      - Deploy, maintain and troubleshoot problems with internal services.
      - Contribute to open source technology including our infrastructure management tool Chef. Research and implement industry standard tools as we scale our site.
      - Maintain and improve our internal package and configuration management systems.
      - In-depth understanding and appreciation of security, durability and availability concerns in distributed environments
      - Create, setup, and run performance tests to help determine optimal hosting configurations
      - Implement disaster recovery and failover systems
      - Strive for the industry unicorn of 99.99% site uptime
      - Monitor overall site performance, stability, and health, including being on call for site issues such as alert handling and disaster recovery. Provide support to deployment and production issues during and off regular office hours.
    requirements:
      - BS in Electrical Engineering, Computer Engineering or Computer Science, or related experience
      - 5+ years experience in supporting systems in a fast-paced environment with a complex distribution system
      - 3+ years of experience working on a high volume website.
      - 3+ years experience in Internet facing applications, security concerns and vulnerability assessment, virtualization, network protocols (HTTP/S, SSL, SSH)
      - Server-side development experience in highly concurrent systems
      - Unrivaled proficiency in Linux server administration, including network tuning.
      - A deep and abiding love for building scalable, high performance systems.
      - Understanding what it means to run a global infrastructure in the Cloud. Knowledge of cloud hosting, specifically Amazon EC2.
      - Experience with a scripting language (Bash, Ruby, and Python) required.
      - Experience configuring a server using a configuration management tool like Chef or Puppet required.
      - Strong systems software, automation techniques, Network Protocols, Web services, Operating System internals, clustering, failover, disaster recovery, database skills and knowledge.
      - Expertise tuning Linux systems for a variety of network traffic, diagnosing network-level issues required.
      - Experience with caching technologies like Memcached.
      - Self-starter, able to work with little or no supervision.
    desireable:
      - Multi-homed websites, virtualization (EC2, xen), Redis experience is a major plus.
      - Experience with ElasticSearch, php5+ and Git is a major plus.
      - Experience with Agile/Scrum desirable.
      - Other Software development experience.
      - Strong communication skills.
      - Strong problem solving and analytic skills.
