pygments: true
exclude: README.md

url: http://engineering.zumba.com
career_email: careers@zumba.com
engineer_email: engineering@zumba.com

permalink: /:year/:month/:day/:title

disqus_short_name: zumbaengineering

analytics_code: UA-33869562-1

share_twitter: true
share_google: true
share_facebook: false
