pygments: true
exclude: README.md

url: http://engineering.zumba.com
career_email: careers@zumba.com
engineer_email: engineering@zumba.com

permalink: /:year/:month/:day/:title

disqus_short_name: zumbaengineering

analytics_code: UA-33869562-1

share_twitter: true
share_google: true
share_facebook: false

authors:
  cjsaylor:
    name: Chris Saylor
    email: christopher.saylor@zumba.com
    github: cjsaylor
    twitter: cjsaylor
    gravatar: 53c40ddf10f397ab4494fc55078125dc
  jrbasso:
    name: Juan Basso
    email: juan.basso@zumba.com
    github: jrbasso
    twitter: jrbasso
    gravatar: 1333d11249a2ed342d612c49a7c1e913
